### ISSUE TITLE
How can I use it in 4.13?or higher?

### ISSUE THREAD

**Issue by oOtroyOo** [mitchemmc/VRUMGPlugin#2]
you said " It should be ready for 4.13",under the youtube video . but I could only found 4.12 version.
I want to use the VR example template in 4.13, but I can't build the plugin in this version . It shows some errors, I don't know to fix them.

**Comment by mitchemmc** [comment]
Please use the in built method for interacting with widgets available in 4.13 as this plugin is now deprecated https://docs.unrealengine.com/latest/INT/Engine/UMG/UserGuide/WidgetInteraction/
